# Generated by Django 5.2.5 on 2025-08-19 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название скрипта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('script_type', models.CharField(choices=[('hh_parser', 'HeadHunter Parser'), ('other', 'Other')], default='hh_parser', max_length=50, verbose_name='Тип скрипта')),
                ('search_query', models.CharField(default='Инженер по охране труда', max_length=200, verbose_name='Поисковый запрос')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время запуска')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('total_found', models.IntegerField(default=0, verbose_name='Всего найдено')),
                ('new_vacancies', models.IntegerField(default=0, verbose_name='Новых вакансий')),
                ('existing_vacancies', models.IntegerField(default=0, verbose_name='Существующих вакансий')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('log_data', models.TextField(blank=True, verbose_name='Лог выполнения')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scripts.script', verbose_name='Скрипт')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запущен пользователем')),
            ],
            options={
                'verbose_name': 'Запуск скрипта',
                'verbose_name_plural': 'Запуски скриптов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('company', models.CharField(max_length=300, verbose_name='Компания')),
                ('salary', models.CharField(max_length=200, verbose_name='Зарплата')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новая вакансия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена в систему')),
                ('script_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='scripts.scriptrun', verbose_name='Запуск скрипта')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
                'unique_together': {('external_id', 'script_run')},
            },
        ),
    ]
