# Generated by Django 5.2.5 on 2025-08-19 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-last_seen_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Первое обнаружение'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная (ещё существует на сайте)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обнаружение'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='scripts.script', verbose_name='Скрипт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='times_found',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество обнаружений'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='script_run',
        ),
        migrations.CreateModel(
            name='VacancyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_in_run', models.BooleanField(default=True, verbose_name='Новая в этом запуске')),
                ('found_at', models.DateTimeField(auto_now_add=True, verbose_name='Найдена в запуске')),
                ('script_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_runs', to='scripts.scriptrun', verbose_name='Запуск скрипта')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scripts.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Вакансия в запуске',
                'verbose_name_plural': 'Вакансии в запусках',
                'unique_together': {('script_run', 'vacancy')},
            },
        ),
    ]
