# Generated by Django 5.2.5 on 2025-08-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_alter_vacancy_options_alter_vacancy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='scripts.script', verbose_name='Скрипт'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('script', 'external_id')},
        ),
    ]
