# Generated by Django 5.2.5 on 2025-08-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_alter_vacancy_script_alter_vacancy_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='max_pages',
            field=models.PositiveIntegerField(default=20, help_text='Максимальное количество страниц для загрузки (по умолчанию 20 - лимит API HH.ru)', verbose_name='Максимальное количество страниц'),
        ),
    ]
