# Generated by Django 5.2.5 on 2025-08-20 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_script_max_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, которые имеют доступ к этому скрипту', related_name='accessible_scripts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи с доступом'),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scripts', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем'),
        ),
    ]
