# Generated by Django 5.2.5 on 2025-08-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_script_allowed_users_alter_script_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='region',
            field=models.CharField(choices=[('1', 'Москва'), ('2', 'Санкт-Петербург'), ('1002', 'Московская область'), ('2019', 'Ленинградская область'), ('moscow_mo', 'Москва и МО'), ('all', 'Вся Россия')], default='moscow_mo', help_text='Регион для поиска вакансий', max_length=20, verbose_name='Регион поиска'),
        ),
        migrations.AddField(
            model_name='script',
            name='search_queries',
            field=models.TextField(default='["Инженер по охране труда", "Специалист по охране труда"]', help_text='JSON массив поисковых запросов, например: ["запрос1", "запрос2"]', verbose_name='Поисковые запросы (JSON)'),
        ),
        migrations.AddField(
            model_name='scriptrun',
            name='queries_stats',
            field=models.TextField(blank=True, help_text='JSON с детальной статистикой по каждому поисковому запросу', verbose_name='Статистика по запросам'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='area_name',
            field=models.CharField(blank=True, help_text='Название региона/города', max_length=200, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='found_by_query',
            field=models.CharField(blank=True, help_text='Поисковый запрос, по которому найдена вакансия', max_length=200, verbose_name='Найдено по запросу'),
        ),
        migrations.AddField(
            model_name='vacancyrun',
            name='found_by_query',
            field=models.CharField(blank=True, help_text='Поисковый запрос, по которому найдена вакансия в этом запуске', max_length=200, verbose_name='Найдено по запросу'),
        ),
        migrations.AlterField(
            model_name='script',
            name='search_query',
            field=models.CharField(default='Инженер по охране труда', help_text='Используется для совместимости со старыми скриптами', max_length=200, verbose_name='Поисковый запрос (устаревшее)'),
        ),
    ]
